ENH: Using ITKMontage module in the most basic way
BlueQuartzSoftware/MultiscaleFusion pull request #7
Opened 2018-11-21 22:12 UTC by dzenanz

This produces something when pointed at `C:\Misc\BlueQuartz\ITKMontage\test\Input\FlatField\14`, and ParaView 5.6.0 can visualize it.

2018-11-27 16:40 UTC, thewtex requested changes

2018-11-27 16:40 UTC, thewtex commented on Documentation/MultiscaleFusionFilters/ITKMontageFromFilesystem.md
> +MyFilter
Give me a name :-)

2018-11-27 16:40 UTC, thewtex commented on Documentation/MultiscaleFusionFilters/ITKMontageFromFilesystem.md
> +This **Filter** does the following...
Describe me

2018-11-27 16:40 UTC, thewtex commented on Documentation/MultiscaleFusionFilters/ITKMontageFromFilesystem.md
> +| Parameter Name | Parameter Type | Description of parameter... |
Describe the file list use

2018-11-27 16:40 UTC, thewtex commented on Documentation/MultiscaleFusionFilters/ITKMontageFromFilesystem.md
> +| **Element/Feature/Ensemble/etc. Attribute Array** | AttributeArray Name | int32_t/float/etc. | (1)/(3)/etc. | Description of object... |
What is the destination montage, the destination transforms

2018-11-27 16:40 UTC, thewtex commented on Documentation/MultiscaleFusionFilters/ITKMontageFromFilesystem.md
> +Please see the description file distributed with this plugin.
Add license and copyright file

2018-11-27 16:40 UTC, thewtex commented on MultiscaleFusionFilters/ITKMontageFromFilesystem.h
> +  SIMPL_FILTER_PARAMETER(IntVec3_t, MontageSize)
Document

2018-11-27 16:40 UTC, thewtex commented on MultiscaleFusionFilters/ITKMontageFromFilesystem.h
> +
also test input where there is no tile configuration

Add overlap as a parameter, have a good default

2018-12-04 18:32 UTC, thewtex commented
I am running into the following build error:

```
In file included from /home/matt/src/SIMPL/Source/SIMPLib/ITK/itkDream3DITransformContainerToTransform.h:87:0,
                 from /home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkDream3DITransformContainerToTransformTest.cpp:36,
                 from SIMPLView/SIMPL/SIMPLib/Testing/SIMPLUnitTest.cpp:40:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkDream3DITransformContainerToTransform.h: In instantiation of ‘class itk::Dream3DITransformContainerToTransform<float, 3>’:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkDream3DITransformContainerToTransformTest.cpp:53:15:   required from here
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkDream3DITransformContainerToTransform.hxx:89:1: error: ‘void itk::Dream3DITransformContainerToTransform<TParametersValueType, CompositeNDimensions>::VerifyPreconditions() [with TParametersValueType = float; unsigned int CompositeNDimensions = 3]’ marked ‘override’, but does not override
 Dream3DITransformContainerToTransform<TParametersValueType, CompositeNDimensions>
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matt/src/SIMPL/Source/SIMPLib/ITK/itkDream3DTransformContainerToTransform.h:78:0,
                 from /home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkDream3DTransformContainerToTransformTest.cpp:34,
                 from SIMPLView/SIMPL/SIMPLib/Testing/SIMPLUnitTest.cpp:41:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkDream3DTransformContainerToTransform.h: In instantiation of ‘class itk::Dream3DTransformContainerToTransform<itk::AffineTransform<float, 3> >’:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkDream3DTransformContainerToTransformTest.cpp:53:15:   required from here
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkDream3DTransformContainerToTransform.hxx:85:1: error: ‘void itk::Dream3DTransformContainerToTransform<ITKTransformType>::VerifyPreconditions() [with ITKTransformType = itk::AffineTransform<float, 3>]’ marked ‘override’, but does not override
 Dream3DTransformContainerToTransform<ITKTransformType>
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DTransformContainer.h:78:0,
                 from /home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkTransformToDream3DTransformContainerTest.cpp:34,
                 from SIMPLView/SIMPL/SIMPLib/Testing/SIMPLUnitTest.cpp:42:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DTransformContainer.h: In instantiation of ‘class itk::TransformToDream3DTransformContainer<itk::AffineTransform<float, 3> >’:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkTransformToDream3DTransformContainerTest.cpp:55:15:   required from here
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DTransformContainer.hxx:85:1: error: ‘void itk::TransformToDream3DTransformContainer<ITKTransformType>::VerifyPreconditions() [with ITKTransformType = itk::AffineTransform<float, 3>]’ marked ‘override’, but does not override
 TransformToDream3DTransformContainer<ITKTransformType>
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DITransformContainer.h:81:0,
                 from /home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkTransformToDream3DITransformContainerTest.cpp:33,
                 from SIMPLView/SIMPL/SIMPLib/Testing/SIMPLUnitTest.cpp:43:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DITransformContainer.h: In instantiation of ‘class itk::TransformToDream3DITransformContainer<float, 3>’:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkTransformToDream3DITransformContainerTest.cpp:54:15:   required from here
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DITransformContainer.hxx:86:1: error: ‘void itk::TransformToDream3DITransformContainer<TParametersValueType, CompositeNDimensions>::VerifyPreconditions() [with TParametersValueType = float; unsigned int CompositeNDimensions = 3]’ marked ‘override’, but does not override
 TransformToDream3DITransformContainer<TParametersValueType, CompositeNDimensions>
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[395/1105] Building CXX object SIMPLView/SIMPL/SVWidgetsLib/CMakeFiles/SVWidgetsLib.dir/FilterParameterWidgets/ReadASCIIDataWidget.cpp.o

```

2018-12-04 19:55 UTC, joeykleingers commented
This build error is occurring because we haven't updated SIMPLib to support ITK 5 yet.  We do, however, have the updates sitting on a branch called OSD_GUI on the SIMPL repo.  I just created a branch on the MultiscaleFusion repo called OSD_GUI as well.  If you guys could set this pull request to go into the OSD_GUI branch instead of develop, then we can continue development on the OSD_GUI branches until we are ready to merge everything into develop.

2018-12-04 20:10 UTC, closed without merging

2018-12-04 20:33 UTC, dzenanz commented
@thewtex this is supposed to build against a slightly [modified](https://github.com/dzenanz/DREAM3DSuperbuild/commit/f309b6718a6bee0fdaeecd05f20141d88e3cdfe8) super-build.